apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ..\..\Software\kompose.exe convert -f docker-compose-edit.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: pulsar
  name: pulsar
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pulsar
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ..\..\Software\kompose.exe convert -f docker-compose-edit.yml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: pulsar
    spec:
      containers:
        - args:
            - bin/pulsar
            - standalone
          image: apachepulsar/pulsar:2.9.1
          name: pulsar
          ports:
            - containerPort: 6650
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /pulsar/data
              name: pulsardata
            - mountPath: /pulsar/conf
              name: pulsarconf
      restartPolicy: Always
      volumes:
        - name: pulsardata
          persistentVolumeClaim:
            claimName: pulsardata
        - name: pulsarconf
          persistentVolumeClaim:
            claimName: pulsarconf
status: {}
