apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ..\..\Software\kompose.exe convert -f docker-compose-edit.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: webprotege-gwt-ui-server
  name: webprotege-gwt-ui-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: webprotege-gwt-ui-server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: ..\..\Software\kompose.exe convert -f docker-compose-edit.yml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: webprotege-gwt-ui-server
    spec:
      containers:
        - env:
            - name: minio.access.key
              value: minioadmin
            - name: minio.access.secret
              value: minioadmin
            - name: minio.endPoint
              value: http://minio:9000
            - name: webprotege.gwt-api-gateway.endPoint
              value: http://webprotege-gwt-api-gateway:7777
          image: protegeproject/webprotege-gwt-ui-server:5.0.0-SNAPSHOT
          name: webprotege-gwt-ui-server
          resources: {}
      restartPolicy: Always
status: {}
