apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ..\..\Software\kompose.exe convert -f docker-compose-edit.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: webprotege-backend-service
  name: webprotege-backend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: webprotege-backend-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ..\..\Software\kompose.exe convert -f docker-compose-edit.yml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: webprotege-backend-service
    spec:
      containers:
        - env:
            - name: spring.data.mongodb.database
              value: webprotege
            - name: spring.data.mongodb.host
              value: mongo
            - name: spring.zipkin.baseUrl
              value: http://zipkin:9411
            - name: webprotege.directories.data
              value: /srv/webprotege
            - name: webprotege.pulsar.command-replies.subscriptionExpiraryTimeMinutes
              value: "5"
            - name: webprotege.pulsar.serviceHttpUrl
              value: http://pulsar:8080
            - name: webprotege.pulsar.serviceUrl
              value: pulsar://pulsar:6650
            - name: webprotege.pulsar.tenant
              value: webprotege
          image: protegeproject/webprotege-backend-service:0.1.1
          name: webprotege-backend-service
          resources: {}
          volumeMounts:
            - mountPath: /srv/webprotege
              name: webprotege-data-directory
      restartPolicy: Always
      volumes:
        - name: webprotege-data-directory
          persistentVolumeClaim:
            claimName: webprotege-data-directory
status: {}
