apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ..\..\Software\kompose.exe convert -f docker-compose-edit.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: zipkin
  name: zipkin
spec:
  ports:
    - name: "9411"
      port: 9411
      targetPort: 9411
  selector:
    io.kompose.service: zipkin
status:
  loadBalancer: {}
